source 'https://rubygems.org'
ruby '>=2.4.0'
gem 'rake'
gem 'test-kitchen'
gem 'kitchen-docker'
gem 'kitchen-openstack'
gem 'kitchen-inspec'
gem 'inspec', '<3.0.0'
#Version was frozen, because of issues in the version of inspec >3.0.0 -- see https://mirantis.jira.com/browse/PROD-24324 for more info
gem 'kitchen-salt', :git => 'https://github.com/salt-formulas/kitchen-salt.git'